<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HP-5CG1482SWP" failures="2" tests="21" name="Default test" time="117.193" errors="0" timestamp="2025-10-19T22:31:01 IST">
  <testcase classname="com.poc.tests.Test1" name="Add_Products_To_Cart_Validation" time="7.05"/>
  <testcase classname="com.poc.tests.Test1" name="Add_Recommended_Products_Validation" time="0.057">
    <failure type="java.lang.AssertionError" message="Recommended product Wnter Top not found">
      <![CDATA[java.lang.AssertionError: Recommended product Wnter Top not found
at org.testng.Assert.fail(Assert.java:111)
at com.poc.pages.Poc_Home_page.selectRecommendedProductandAddtoCart(Poc_Home_page.java:216)
at com.poc.tests.Test1.Add_Recommended_Products_Validation(Test1.java:367)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Add_Recommended_Products_Validation -->
  <testcase classname="com.poc.tests.Test1" name="Add_Recommended_Products_Validation" time="2.106"/>
  <testcase classname="com.poc.tests.Test1" name="Add_Recommended_Products_Validation" time="1.748"/>
  <testcase classname="com.poc.tests.Test1" name="Add_Review_On_Product_Validation" time="3.129"/>
  <testcase classname="com.poc.tests.Test1" name="Contact_Us_Form_Validation" time="2.353"/>
  <testcase classname="com.poc.tests.Test1" name="Invalid_Login_Validation" time="1.276"/>
  <testcase classname="com.poc.tests.Test1" name="Login_Validation" time="1.319">
    <failure type="java.lang.AssertionError" message="User login failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User login failed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.poc.tests.Test1.Login_Validation(Test1.java:88)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Login_Validation -->
  <testcase classname="com.poc.tests.Test1" name="Logout_Validation" time="4.143"/>
  <testcase classname="com.poc.tests.Test1" name="Product_Quantity_In_Cart_Validation" time="2.448"/>
  <testcase classname="com.poc.tests.Test1" name="Register_User_Validation" time="5.668"/>
  <testcase classname="com.poc.tests.Test1" name="Register_User_With_Existing_Email_Validation" time="1.327"/>
  <testcase classname="com.poc.tests.Test1" name="Remove_Product_From_Cart_Validation" time="2.19"/>
  <testcase classname="com.poc.tests.Test1" name="Scroll_Up_Without_Using_Arrow_And_Scroll_down_Validation" time="0.076"/>
  <testcase classname="com.poc.tests.Test1" name="Scroll_Up_using_Arrow_And_Scroll_down_Validation" time="0.106"/>
  <testcase classname="com.poc.tests.Test1" name="Search_Products_Validation" time="3.904"/>
  <testcase classname="com.poc.tests.Test1" name="Subscription_Validation" time="0.169"/>
  <testcase classname="com.poc.tests.Test1" name="Testcases_Page_Validation" time="0.61"/>
  <testcase classname="com.poc.tests.Test1" name="View_Brand_Products_Validation" time="3.944"/>
  <testcase classname="com.poc.tests.Test1" name="View_Category_Products_Validation" time="8.205"/>
  <testcase classname="com.poc.tests.Test1" name="scubscription_In_Cart_Page_Validation" time="1.203"/>
</testsuite> <!-- Default test -->
